sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: mvdLrvjofDYJ59DX9HDd37ZzN1Rd/+J7ZmKvFx4n4uh+xIfywS8bNDw3sdDIEzsZf2kSUa8wcYenkm9DnbyMUfOpOVPWiT4xl8nWvarPRyISRzMJsrAi84KgQXY31mKQMrZAM6SRXGJqsVCpRUFWKMiAQioQGOzTrOqKhk3BKz2xRUPyhhLp4ciqwMK03y4b8VUxasA4tP21+U0yS9hL8SF2FGXCHgjPipuH91MWVBeykpXBB6pVQ5aUvF1uYOzRQx0ef5DpMYhP5HAepUcNT6uExaNiWpVLsDDEzfhfel4gFrQexrzSpgzt4PNf2ug7vpkWHzaMEKqg18W4hayuIGMSJXOeAf03UpEOqsngxkoLZ2TUTuaK5vPtdwmkTIkGQFs/H3ZEfQ74L9uc/dEcttHs3GVKdhHKW1u7QUjt4C+TTMqZJU41FpiOZuy6WkeRVm/Oj3JX5kgVatS3UIxJnQMG2fcdyHZFf5oajNYUe5w1XXyYlhob6tCbCiuqMHZ5+PI9xlKbLRs/Zgpj61XOMpOW0jZRg5/rZ9nHS1WKz2ThES81igA7r3gCIfq7N3YZZKPctIbc3UCJLtKBq/DLsTenVliTfaoNst7IjtouR7hUbuEnGChWTaNVj3Rz0gSZeCKh1dYHvtyWh6k7YT1sOttaYgFV/nobmYllMJLt+JQ=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: QJomR+aeL5/oCvHCWYX0+7sA09Rkua+R/7hVMMMDr+60PfGB/KZhQff1erlCbRjjCwaMVHXVe7eDa22MV7HWJ0N5SJQcjQLEeiqDMApSxzNYjvhCiHlSVy5x2ih3Zzdd6NGEp0e92wEBlCOOvi3gp4wcfU9HKOUIfKOWsZO7vKWCJIPL2X414KCv+CqmogPK9EBFgzFJH+srWmQ8hxFMfRCQZUgA0QkwCo6uLL0V1tutKRrgL3RgNVqhYB1t2RDUTqB2lhr9Vgun00oXfj6WKG83fOvRuMtpVBw0ODtZ/dlnvnBChGpC75TKo9/jNstEJQMCG+LYKL7eoUU6/Y/hIV89Ax27oVHPXZecSVqIdpH4kI/Croc2WVAnF9NB2h4i7Fw+gJljr86m/urWOLka9tjK2Ydo7Acm132ISEZd2KdERvXRYcO9tRDfZ1EFNUIrxjUg9dr+MMTYOlSNlPn2WuDvNlbte+1MRCL80Qokj9aqKsUdqBieePCxgbdqdin7KBN6DSgU+2KwkOyO5rmA4qSXDpBUiBXpiWXDp4bFJvfopaOUj891761Q9gP2tjFTHm8p07r93T+4/KtfBFzRbbLE11KdffRMhigkyGBosvNYs3uT2bS426RrTttqifKueMCiKsarqZfr+Sec7oUvv6jz3HA4IkDcniHytIcj+l8=
